apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sca-genai-api-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "sca-genai-assistant-api"
          objectType: "secretsmanager"
